name = "better-cart-site"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "better-cart"
database_id = "b47e8465-9984-4d34-a1c2-f6b35d53425d"

[[services]]
binding = "API_WORKER"
service = "better-cart-api"

[vars]
API_BASE = "https://api.bettercart.earth"
